---
linters:
  # disable-all: false
  # presets:
  #   - bugs
  #   - unused
  # fast: false

linters-settings:

  # # make function length a bit less strict
  # funlen:
  #   lines: 150
  #   statements: 80

  # # don't report simplifications
  # gofmt:
  #   simplify: false

  # # tolerate up to 130 chars per line
  # lll:
  #   line-length: 130

  # cyclop:
  #   # the maximal code complexity to report
  #   max-complexity: 20
